# Chromosomes to use for GWAS
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 19]

build: '37'

# Each of these will be subdirectories of your working/project directory
saige_cohorts: ['UKBB_AFR', 'UKBB_EUR', 'UKBB_ASIAN']
sex_strat_cohorts: [] # for use when defining different covariates in sex-stratified cohorts

# Lists of phenotypes and covariates to use
quant_phenos: []
bin_phenos: ['endometriosis', 'cluster_vs_controls_1', 'cluster_vs_controls_2', 'cluster_vs_controls_3', 'cluster_vs_controls_4', 'cluster_vs_controls_5']
cat_covars: [] # categorical
cont_covars: ['CURRENT_AGE', 'PC1', 'PC2', 'PC3', 'PC4']

sex_strat_covars: # for use when defining different covariates in sex-stratified cohorts
    cat_covars: [ ] # categorical
    cont_covars: [ ]

# Genotype fileset
QC_Plink_Prefix: '/project/ritchie/datasets/UKBiobank/Merged_Genotype/UKBB_genotype_merged_autosomes'
QC_Plink_Flag: '--bfile'
QC_Plink_Extensions: ['.bed', '.bim', '.fam']

# BGEN file sets
Step2_BGEN_Prefix: '/project/ritchie/datasets/UKBiobank/BGEN_Symlinks/ukb_imp_chr'
Step2_BGEN_Suffix: '_v3'
Step2_BGEN_Sample: '/project/ritchie/datasets/UKBiobank/ukb_genotype_fam/imputed/ukb32133_imp_chr22_v3_s487324.sample'
Step2_BGEN_Allele_Order: 'ref-first'

# Plink2 filesets used to create SNP lists
Step2_PGEN_Prefix: 'Endo_Loci_UKBB/subset.'
Step2_PGEN_Suffix: ''

# Some bgen datasets have "chr22" and some have just "22" which can mess with SAIGE being able to find variants
# For PMBB, this value is True. For UKBB, this value is False
CHR_has_chr_prefix: False
# Has Leading 0 is True for UKBB
# single digit chromosomes are labeled 01-09 for some reason
# and for some other reason, SAIGE doesn't know that 01 == 1
CHR_has_leading_0: True

# Step 2 Options
min_mac: '20'
min_info: '0.4'

# Merge Options - map REGENIE columns to column names that you want. Add/remove key/value pairs as needed
col_names:
    MarkerID: 'ID'
    p.value: 'P'
